name: flutter_file_view_example
description: Demonstrates how to use the flutter_file_view plugin.

publish_to: 'none'

version: 2.0.0+20

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.0.9

  flutter_file_view:
    path: ../

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/files/
